In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('student.csv')

In [12]:
df

    Name   Age  Marks      City
0   Sara  18.0   20.0    lahore
1    Ail  20.0   57.0   karachi
2  Ahmad  45.0    NaN  islambad
3  Aysha  30.0   46.0    gujrat
4  Usman   NaN   43.0       NaN

In [13]:
df.shape

(5, 4)

In [18]:
df.head

<bound method NDFrame.head of     Name   Age  Marks      City
0   Sara  18.0   20.0    lahore
1    Ail  20.0   57.0   karachi
2  Ahmad  45.0    NaN  islambad
3  Aysha  30.0   46.0    gujrat
4  Usman   NaN   43.0       NaN>

In [14]:
df.columns

Index(['Name', 'Age', 'Marks', 'City'], dtype='str')

In [15]:
df.info

<bound method DataFrame.info of     Name   Age  Marks      City
0   Sara  18.0   20.0    lahore
1    Ail  20.0   57.0   karachi
2  Ahmad  45.0    NaN  islambad
3  Aysha  30.0   46.0    gujrat
4  Usman   NaN   43.0       NaN>

In [17]:
df.describe()

             Age      Marks
count   4.000000   4.000000
mean   28.250000  41.500000
std    12.338963  15.545632
min    18.000000  20.000000
25%    19.500000  37.250000
50%    25.000000  44.500000
75%    33.750000  48.750000
max    45.000000  57.000000

In [19]:
df['Name']

0     Sara
1      Ail
2    Ahmad
3    Aysha
4    Usman
Name: Name, dtype: str

In [20]:
df[['Age','Marks']]

    Age  Marks
0  18.0   20.0
1  20.0   57.0
2  45.0    NaN
3  30.0   46.0
4   NaN   43.0

In [21]:
df.loc[0]

Name       Sara
Age        18.0
Marks      20.0
City     lahore
Name: 0, dtype: object

In [22]:
df[df['Marks'] > 40]

    Name   Age  Marks     City
1    Ail  20.0   57.0  karachi
3  Aysha  30.0   46.0   gujrat
4  Usman   NaN   43.0      NaN

In [23]:
df[df['Marks'] < 40]

   Name   Age  Marks    City
0  Sara  18.0   20.0  lahore

In [24]:
df.isnull()

    Name    Age  Marks   City
0  False  False  False  False
1  False  False  False  False
2  False  False   True  False
3  False  False  False  False
4  False   True  False   True

In [25]:
df.isnull().sum()

Name     0
Age      1
Marks    1
City     1
dtype: int64

In [26]:
df

    Name   Age  Marks      City
0   Sara  18.0   20.0    lahore
1    Ail  20.0   57.0   karachi
2  Ahmad  45.0    NaN  islambad
3  Aysha  30.0   46.0    gujrat
4  Usman   NaN   43.0       NaN

In [28]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [29]:
df

    Name    Age  Marks      City
0   Sara  18.00   20.0    lahore
1    Ail  20.00   57.0   karachi
2  Ahmad  45.00    NaN  islambad
3  Aysha  30.00   46.0    gujrat
4  Usman  28.25   43.0       NaN

In [30]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [31]:
df

    Name    Age  Marks      City
0   Sara  18.00   20.0    lahore
1    Ail  20.00   57.0   karachi
2  Ahmad  45.00   41.5  islambad
3  Aysha  30.00   46.0    gujrat
4  Usman  28.25   43.0       NaN

In [32]:
mode_city = df['City'].mode()[0]

In [33]:
df['City'] = df['City'].fillna(mode_city)

In [34]:
df

    Name    Age  Marks      City
0   Sara  18.00   20.0    lahore
1    Ail  20.00   57.0   karachi
2  Ahmad  45.00   41.5  islambad
3  Aysha  30.00   46.0    gujrat
4  Usman  28.25   43.0    gujrat

In [35]:
df['Marks'].min()

np.float64(20.0)

In [36]:
df['Marks'].max()

np.float64(57.0)

In [44]:
df["result"] = df['Marks'].apply(lambda x: "pass" if x<=50  else "fail")

In [45]:
df

    Name    Age  Marks      City result
0   Sara  18.00   20.0    lahore   pass
1    Ail  20.00   57.0   karachi   fail
2  Ahmad  45.00   41.5  islambad   pass
3  Aysha  30.00   46.0    gujrat   pass
4  Usman  28.25   43.0    gujrat   pass

In [ ]:
df.head()